# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 199)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/black/icons/black/Layer 1 copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("/* Global Styles */\n"
"* {\n"
"    font: 10pt \"Segoe UI\", Tahoma, Geneva, Verdana, sans-serif;;\n"
"    color: #333; /* Koyu gri yazı rengi */\n"
"    margin: 0;\n"
"    padding: 0;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Etiketler */\n"
"QLabel {\n"
"    color: #333; /* Koyu gri yazı rengi */\n"
"    font-weight: 500; /* Orta kalınlıkta yazı */\n"
"}\n"
"\n"
"/* Butonlar */\n"
"QPushButton {\n"
"    color: #fff; /* Beyaz yazı rengi */\n"
"    background-color: #007bff; /* Modern mavi arka plan */\n"
"    border: none;\n"
"    border-radius: 6px; /* Hafif yuvarlatılmış köşeler */\n"
"    padding: 8px 20px; /* Rahat içerik alanı */\n"
"    margin: 5px;\n"
"    font-weight: 600; /* Kalın yazı */\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Üzerine gelindiğinde koyu mavi */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004080; /* Tıklama anında daha koyu mavi */\n"
"}\n"
"\n"
"/* Araç Butonları */\n"
"QToolButton {\n"
"    color: #333;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    font-weight: 600;\n"
"    text-align: center;\n"
"    font-size: 12px; /* Yazı boyutu ayarlandı */\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #e0e0e0; /* Üzerine gelindiğinde hafif gri */\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: #d0d0d0; /* Tıklama anında daha koyu gri */\n"
"}\n"
"\n"
"/* Giriş Alanları */\n"
"QLineEdit, QPlainTextEdit {\n"
"    color: #333;\n"
"    background-color: #fff; /* Beyaz arka plan */\n"
"    border: 1px solid #ccc; /* Açık gri sınır */\n"
"    border-radius: 4px; /* Hafif yuvarlatılmış köşeler */\n"
"    font-size: 14px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QLineEdit:focus, QPlainTextEdit:focus {\n"
"    border-color: #007bff; /* Odaklanıldığında mavi sınır */\n"
"}\n"
"\n"
"/* Seçim Kutuları */\n"
"QComboBox {\n"
"    color: #333;\n"
"    background-color: #fff;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-left: 1px solid #ccc; /* Düğme ile kutuyu ayır */\n"
"}\n"
"\n"
"/* Menüler ve Menü Çubuğu */\n"
"QMenuBar {\n"
"    background-color: #007bff;\n"
"    color: #fff;\n"
"    padding: 0 10px;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    padding: 10px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #0056b3;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #fff;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #007bff;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background-color: #ccc;\n"
"    margin: 5px 0;\n"
"}\n"
"\n"
"/* Checkbox ve Radio Butonlar */\n"
"QCheckBox, QRadioButton {\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator, QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    background-color: #007bff;\n"
"    border: 1px solid #007bff;\n"
"}\n"
"\n"
"/* Tablolar */\n"
"QTableWidget {\n"
"    background-color: #fff;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #007bff;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #ccc;\n"
"    padding: 8px;\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Kaydırıcılar */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: #f5f5f5;\n"
"    border: none;\n"
"    width: 12px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: #ccc;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"    width: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* GroupBox */\n"
"QGroupBox {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    margin: 10px;\n"
"    padding: 10px;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 10px;\n"
"    color: #333;\n"
"    font-weight: 600;\n"
"    font-size: 16px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerFrame = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerFrame.sizePolicy().hasHeightForWidth())
        self.headerFrame.setSizePolicy(sizePolicy)
        self.headerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.headerFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.headerPNG = QtWidgets.QLabel(self.headerFrame)
        self.headerPNG.setMinimumSize(QtCore.QSize(24, 24))
        self.headerPNG.setMaximumSize(QtCore.QSize(24, 24))
        self.headerPNG.setText("")
        self.headerPNG.setPixmap(QtGui.QPixmap(":/imgs/icons/img/12.ico"))
        self.headerPNG.setScaledContents(True)
        self.headerPNG.setObjectName("headerPNG")
        self.horizontalLayout_2.addWidget(self.headerPNG)
        self.headerWord = QtWidgets.QLabel(self.headerFrame)
        self.headerWord.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.headerWord.setFont(font)
        self.headerWord.setObjectName("headerWord")
        self.horizontalLayout_2.addWidget(self.headerWord)
        self.spin_giris_sezon_baslangic = QtWidgets.QSpinBox(self.headerFrame)
        self.spin_giris_sezon_baslangic.setReadOnly(False)
        self.spin_giris_sezon_baslangic.setKeyboardTracking(False)
        self.spin_giris_sezon_baslangic.setMinimum(2023)
        self.spin_giris_sezon_baslangic.setMaximum(9998)
        self.spin_giris_sezon_baslangic.setObjectName("spin_giris_sezon_baslangic")
        self.horizontalLayout_2.addWidget(self.spin_giris_sezon_baslangic)
        self.line_5 = QtWidgets.QFrame(self.headerFrame)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_2.addWidget(self.line_5)
        self.spin_giris_sezon_bitis = QtWidgets.QSpinBox(self.headerFrame)
        self.spin_giris_sezon_bitis.setReadOnly(True)
        self.spin_giris_sezon_bitis.setMinimum(2024)
        self.spin_giris_sezon_bitis.setMaximum(9999)
        self.spin_giris_sezon_bitis.setObjectName("spin_giris_sezon_bitis")
        self.horizontalLayout_2.addWidget(self.spin_giris_sezon_bitis)
        self.btn_sezonKaydet = QtWidgets.QPushButton(self.headerFrame)
        self.btn_sezonKaydet.setObjectName("btn_sezonKaydet")
        self.horizontalLayout_2.addWidget(self.btn_sezonKaydet)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.line = QtWidgets.QFrame(self.headerFrame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.userFrame = QtWidgets.QFrame(self.headerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userFrame.sizePolicy().hasHeightForWidth())
        self.userFrame.setSizePolicy(sizePolicy)
        self.userFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.userFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.userFrame.setObjectName("userFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.userFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.UserPNG = QtWidgets.QFrame(self.userFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserPNG.sizePolicy().hasHeightForWidth())
        self.UserPNG.setSizePolicy(sizePolicy)
        self.UserPNG.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UserPNG.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UserPNG.setObjectName("UserPNG")
        self.gridLayout = QtWidgets.QGridLayout(self.UserPNG)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.UserPNG)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/black/icons/black/user-check.svg"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.UserPNG, 0, QtCore.Qt.AlignRight)
        self.UsernameText = QtWidgets.QFrame(self.userFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsernameText.sizePolicy().hasHeightForWidth())
        self.UsernameText.setSizePolicy(sizePolicy)
        self.UsernameText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UsernameText.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UsernameText.setObjectName("UsernameText")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.UsernameText)
        self.gridLayout_2.setContentsMargins(5, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_username = QtWidgets.QLabel(self.UsernameText)
        self.label_username.setObjectName("label_username")
        self.gridLayout_2.addWidget(self.label_username, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.UsernameText, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_2.addWidget(self.userFrame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.headerFrame)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu_btn_ogrenci_ekle = QtWidgets.QToolButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn_ogrenci_ekle.sizePolicy().hasHeightForWidth())
        self.menu_btn_ogrenci_ekle.setSizePolicy(sizePolicy)
        self.menu_btn_ogrenci_ekle.setMaximumSize(QtCore.QSize(63, 64))
        self.menu_btn_ogrenci_ekle.setAutoFillBackground(False)
        self.menu_btn_ogrenci_ekle.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/others/icons/others/student-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn_ogrenci_ekle.setIcon(icon1)
        self.menu_btn_ogrenci_ekle.setIconSize(QtCore.QSize(32, 32))
        self.menu_btn_ogrenci_ekle.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.menu_btn_ogrenci_ekle.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.menu_btn_ogrenci_ekle.setObjectName("menu_btn_ogrenci_ekle")
        self.horizontalLayout_4.addWidget(self.menu_btn_ogrenci_ekle)
        self.menu_btn_kayitli_ogrenciler = QtWidgets.QToolButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn_kayitli_ogrenciler.sizePolicy().hasHeightForWidth())
        self.menu_btn_kayitli_ogrenciler.setSizePolicy(sizePolicy)
        self.menu_btn_kayitli_ogrenciler.setMaximumSize(QtCore.QSize(63, 64))
        self.menu_btn_kayitli_ogrenciler.setAutoFillBackground(False)
        self.menu_btn_kayitli_ogrenciler.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/others/icons/others/discuss-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn_kayitli_ogrenciler.setIcon(icon2)
        self.menu_btn_kayitli_ogrenciler.setIconSize(QtCore.QSize(32, 32))
        self.menu_btn_kayitli_ogrenciler.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.menu_btn_kayitli_ogrenciler.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.menu_btn_kayitli_ogrenciler.setObjectName("menu_btn_kayitli_ogrenciler")
        self.horizontalLayout_4.addWidget(self.menu_btn_kayitli_ogrenciler)
        self.menu_btn_tahsilat_islemi = QtWidgets.QToolButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn_tahsilat_islemi.sizePolicy().hasHeightForWidth())
        self.menu_btn_tahsilat_islemi.setSizePolicy(sizePolicy)
        self.menu_btn_tahsilat_islemi.setMaximumSize(QtCore.QSize(64, 64))
        self.menu_btn_tahsilat_islemi.setAutoFillBackground(False)
        self.menu_btn_tahsilat_islemi.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/others/icons/others/clipboard-report-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn_tahsilat_islemi.setIcon(icon3)
        self.menu_btn_tahsilat_islemi.setIconSize(QtCore.QSize(32, 32))
        self.menu_btn_tahsilat_islemi.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.menu_btn_tahsilat_islemi.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.menu_btn_tahsilat_islemi.setObjectName("menu_btn_tahsilat_islemi")
        self.horizontalLayout_4.addWidget(self.menu_btn_tahsilat_islemi)
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_4.addWidget(self.line_4)
        self.menu_btn_vadesi_gelen_taksitler = QtWidgets.QToolButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn_vadesi_gelen_taksitler.sizePolicy().hasHeightForWidth())
        self.menu_btn_vadesi_gelen_taksitler.setSizePolicy(sizePolicy)
        self.menu_btn_vadesi_gelen_taksitler.setMaximumSize(QtCore.QSize(63, 64))
        self.menu_btn_vadesi_gelen_taksitler.setAutoFillBackground(False)
        self.menu_btn_vadesi_gelen_taksitler.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/others/icons/others/time-management-hourglass-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn_vadesi_gelen_taksitler.setIcon(icon4)
        self.menu_btn_vadesi_gelen_taksitler.setIconSize(QtCore.QSize(32, 32))
        self.menu_btn_vadesi_gelen_taksitler.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.menu_btn_vadesi_gelen_taksitler.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.menu_btn_vadesi_gelen_taksitler.setObjectName("menu_btn_vadesi_gelen_taksitler")
        self.horizontalLayout_4.addWidget(self.menu_btn_vadesi_gelen_taksitler)
        self.menu_btn_vadesi_gecmis_taksitler = QtWidgets.QToolButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn_vadesi_gecmis_taksitler.sizePolicy().hasHeightForWidth())
        self.menu_btn_vadesi_gecmis_taksitler.setSizePolicy(sizePolicy)
        self.menu_btn_vadesi_gecmis_taksitler.setMaximumSize(QtCore.QSize(63, 64))
        self.menu_btn_vadesi_gecmis_taksitler.setAutoFillBackground(False)
        self.menu_btn_vadesi_gecmis_taksitler.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/others/icons/others/time-left-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn_vadesi_gecmis_taksitler.setIcon(icon5)
        self.menu_btn_vadesi_gecmis_taksitler.setIconSize(QtCore.QSize(32, 32))
        self.menu_btn_vadesi_gecmis_taksitler.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.menu_btn_vadesi_gecmis_taksitler.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.menu_btn_vadesi_gecmis_taksitler.setObjectName("menu_btn_vadesi_gecmis_taksitler")
        self.horizontalLayout_4.addWidget(self.menu_btn_vadesi_gecmis_taksitler)
        self.menu_btn_tahsilat_raporu = QtWidgets.QToolButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn_tahsilat_raporu.sizePolicy().hasHeightForWidth())
        self.menu_btn_tahsilat_raporu.setSizePolicy(sizePolicy)
        self.menu_btn_tahsilat_raporu.setMaximumSize(QtCore.QSize(63, 64))
        self.menu_btn_tahsilat_raporu.setAutoFillBackground(False)
        self.menu_btn_tahsilat_raporu.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/others/icons/others/bank-banking-budget-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn_tahsilat_raporu.setIcon(icon6)
        self.menu_btn_tahsilat_raporu.setIconSize(QtCore.QSize(32, 32))
        self.menu_btn_tahsilat_raporu.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.menu_btn_tahsilat_raporu.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.menu_btn_tahsilat_raporu.setObjectName("menu_btn_tahsilat_raporu")
        self.horizontalLayout_4.addWidget(self.menu_btn_tahsilat_raporu)
        spacerItem1 = QtWidgets.QSpacerItem(800, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu_btn_gelir_ekle = QtWidgets.QToolButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn_gelir_ekle.sizePolicy().hasHeightForWidth())
        self.menu_btn_gelir_ekle.setSizePolicy(sizePolicy)
        self.menu_btn_gelir_ekle.setMaximumSize(QtCore.QSize(63, 64))
        self.menu_btn_gelir_ekle.setAutoFillBackground(False)
        self.menu_btn_gelir_ekle.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/others/icons/others/add_green.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn_gelir_ekle.setIcon(icon7)
        self.menu_btn_gelir_ekle.setIconSize(QtCore.QSize(32, 32))
        self.menu_btn_gelir_ekle.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.menu_btn_gelir_ekle.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.menu_btn_gelir_ekle.setObjectName("menu_btn_gelir_ekle")
        self.horizontalLayout.addWidget(self.menu_btn_gelir_ekle)
        self.menu_btn_gider_ekle = QtWidgets.QToolButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn_gider_ekle.sizePolicy().hasHeightForWidth())
        self.menu_btn_gider_ekle.setSizePolicy(sizePolicy)
        self.menu_btn_gider_ekle.setMaximumSize(QtCore.QSize(64, 64))
        self.menu_btn_gider_ekle.setAutoFillBackground(False)
        self.menu_btn_gider_ekle.setStyleSheet("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/others/icons/others/add_red.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn_gider_ekle.setIcon(icon8)
        self.menu_btn_gider_ekle.setIconSize(QtCore.QSize(32, 32))
        self.menu_btn_gider_ekle.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.menu_btn_gider_ekle.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.menu_btn_gider_ekle.setObjectName("menu_btn_gider_ekle")
        self.horizontalLayout.addWidget(self.menu_btn_gider_ekle)
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.menu_btn_cari_goster = QtWidgets.QToolButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn_cari_goster.sizePolicy().hasHeightForWidth())
        self.menu_btn_cari_goster.setSizePolicy(sizePolicy)
        self.menu_btn_cari_goster.setMaximumSize(QtCore.QSize(63, 64))
        self.menu_btn_cari_goster.setAutoFillBackground(False)
        self.menu_btn_cari_goster.setStyleSheet("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/others/icons/others/report-svgrepo-com (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn_cari_goster.setIcon(icon9)
        self.menu_btn_cari_goster.setIconSize(QtCore.QSize(32, 32))
        self.menu_btn_cari_goster.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.menu_btn_cari_goster.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.menu_btn_cari_goster.setObjectName("menu_btn_cari_goster")
        self.horizontalLayout.addWidget(self.menu_btn_cari_goster)
        self.menu_btn_aylik_tablo = QtWidgets.QToolButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn_aylik_tablo.sizePolicy().hasHeightForWidth())
        self.menu_btn_aylik_tablo.setSizePolicy(sizePolicy)
        self.menu_btn_aylik_tablo.setMaximumSize(QtCore.QSize(63, 64))
        self.menu_btn_aylik_tablo.setAutoFillBackground(False)
        self.menu_btn_aylik_tablo.setStyleSheet("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/others/icons/others/report-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn_aylik_tablo.setIcon(icon10)
        self.menu_btn_aylik_tablo.setIconSize(QtCore.QSize(32, 32))
        self.menu_btn_aylik_tablo.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.menu_btn_aylik_tablo.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.menu_btn_aylik_tablo.setObjectName("menu_btn_aylik_tablo")
        self.horizontalLayout.addWidget(self.menu_btn_aylik_tablo)
        self.menu_btn_yillik_tablo = QtWidgets.QToolButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn_yillik_tablo.sizePolicy().hasHeightForWidth())
        self.menu_btn_yillik_tablo.setSizePolicy(sizePolicy)
        self.menu_btn_yillik_tablo.setMaximumSize(QtCore.QSize(63, 64))
        self.menu_btn_yillik_tablo.setAutoFillBackground(False)
        self.menu_btn_yillik_tablo.setStyleSheet("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/others/icons/others/report-svgrepo-com2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn_yillik_tablo.setIcon(icon11)
        self.menu_btn_yillik_tablo.setIconSize(QtCore.QSize(32, 32))
        self.menu_btn_yillik_tablo.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.menu_btn_yillik_tablo.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.menu_btn_yillik_tablo.setObjectName("menu_btn_yillik_tablo")
        self.horizontalLayout.addWidget(self.menu_btn_yillik_tablo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.p_HomePage = QtWidgets.QWidget()
        self.p_HomePage.setObjectName("p_HomePage")
        self.stackedWidget.addWidget(self.p_HomePage)
        self.p_OgrenciEkle = QtWidgets.QWidget()
        self.p_OgrenciEkle.setObjectName("p_OgrenciEkle")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.p_OgrenciEkle)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stackedWidget.addWidget(self.p_OgrenciEkle)
        self.p_TahsilatIslemi = QtWidgets.QWidget()
        self.p_TahsilatIslemi.setObjectName("p_TahsilatIslemi")
        self.stackedWidget.addWidget(self.p_TahsilatIslemi)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HERİKLİ EĞİTİM KURUMLARI"))
        self.headerWord.setText(_translate("MainWindow", "HERİKLİ EĞİTİM KURUMLARI"))
        self.btn_sezonKaydet.setText(_translate("MainWindow", "KAYDET"))
        self.label_username.setText(_translate("MainWindow", ": Admin"))
        self.menu_btn_ogrenci_ekle.setText(_translate("MainWindow", "Öğrenci\n"
"Ekle"))
        self.menu_btn_kayitli_ogrenciler.setText(_translate("MainWindow", "Kayıtlı\n"
"Öğrenciler"))
        self.menu_btn_tahsilat_islemi.setText(_translate("MainWindow", "Tahsilat\n"
"İşlemi"))
        self.menu_btn_vadesi_gelen_taksitler.setText(_translate("MainWindow", "Vadesi Gelen\n"
"Taksitler"))
        self.menu_btn_vadesi_gecmis_taksitler.setText(_translate("MainWindow", "Vadesi Geçen\n"
"Taksitler"))
        self.menu_btn_tahsilat_raporu.setText(_translate("MainWindow", "Tahsilat\n"
"Raporu"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Öğrenci"))
        self.menu_btn_gelir_ekle.setText(_translate("MainWindow", "Gelir\n"
"Ekle"))
        self.menu_btn_gider_ekle.setText(_translate("MainWindow", "Gider\n"
"Ekle"))
        self.menu_btn_cari_goster.setText(_translate("MainWindow", "Cari\n"
"Göster"))
        self.menu_btn_aylik_tablo.setText(_translate("MainWindow", "Aylık\n"
"Tablo"))
        self.menu_btn_yillik_tablo.setText(_translate("MainWindow", "Yıllık\n"
"Tablo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Muhasebe"))
import resources_rc
