# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\kayitli_ogrenciler.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kayitli_ogrenciler(object):
    def setupUi(self, kayitli_ogrenciler):
        kayitli_ogrenciler.setObjectName("kayitli_ogrenciler")
        kayitli_ogrenciler.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/black/icons/black/Layer 1 copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        kayitli_ogrenciler.setWindowIcon(icon)
        kayitli_ogrenciler.setStyleSheet("/* Global Styles */\n"
"* {\n"
"    font: 10pt \"Segoe UI\", Tahoma, Geneva, Verdana, sans-serif;;\n"
"    color: #333; /* Koyu gri yazı rengi */\n"
"    margin: 0;\n"
"    padding: 0;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Etiketler */\n"
"QLabel {\n"
"    color: #333; /* Koyu gri yazı rengi */\n"
"    font-weight: 500; /* Orta kalınlıkta yazı */\n"
"}\n"
"\n"
"/* Butonlar */\n"
"QPushButton {\n"
"    color: #fff; /* Beyaz yazı rengi */\n"
"    background-color: #007bff; /* Modern mavi arka plan */\n"
"    border: none;\n"
"    border-radius: 6px; /* Hafif yuvarlatılmış köşeler */\n"
"    padding: 8px 20px; /* Rahat içerik alanı */\n"
"    margin: 5px;\n"
"    font-weight: 600; /* Kalın yazı */\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Üzerine gelindiğinde koyu mavi */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004080; /* Tıklama anında daha koyu mavi */\n"
"}\n"
"\n"
"/* Araç Butonları */\n"
"QToolButton {\n"
"    color: #333;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    font-weight: 600;\n"
"    text-align: center;\n"
"    font-size: 12px; /* Yazı boyutu ayarlandı */\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #e0e0e0; /* Üzerine gelindiğinde hafif gri */\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: #d0d0d0; /* Tıklama anında daha koyu gri */\n"
"}\n"
"\n"
"/* Giriş Alanları */\n"
"QLineEdit, QPlainTextEdit {\n"
"    color: #333;\n"
"    background-color: #fff; /* Beyaz arka plan */\n"
"    border: 1px solid #ccc; /* Açık gri sınır */\n"
"    border-radius: 4px; /* Hafif yuvarlatılmış köşeler */\n"
"    font-size: 14px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QLineEdit:focus, QPlainTextEdit:focus {\n"
"    border-color: #007bff; /* Odaklanıldığında mavi sınır */\n"
"}\n"
"\n"
"/* Seçim Kutuları */\n"
"QComboBox {\n"
"    color: #333;\n"
"    background-color: #fff;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-left: 1px solid #ccc; /* Düğme ile kutuyu ayır */\n"
"}\n"
"\n"
"/* Menüler ve Menü Çubuğu */\n"
"QMenuBar {\n"
"    background-color: #007bff;\n"
"    color: #fff;\n"
"    padding: 0 10px;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    padding: 10px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #0056b3;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #fff;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #007bff;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background-color: #ccc;\n"
"    margin: 5px 0;\n"
"}\n"
"\n"
"/* Checkbox ve Radio Butonlar */\n"
"QCheckBox, QRadioButton {\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator, QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    background-color: #007bff;\n"
"    border: 1px solid #007bff;\n"
"}\n"
"\n"
"/* Tablolar */\n"
"QTableWidget {\n"
"    background-color: #fff;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #007bff;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #ccc;\n"
"    padding: 8px;\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Kaydırıcılar */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: #f5f5f5;\n"
"    border: none;\n"
"    width: 12px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: #ccc;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"    width: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* GroupBox */\n"
"QGroupBox {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    margin: 10px;\n"
"    padding: 10px;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 10px;\n"
"    color: #333;\n"
"    font-weight: 600;\n"
"    font-size: 16px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(kayitli_ogrenciler)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_kayitli_ogrenciler_listeyi_yenile = QtWidgets.QToolButton(self.frame_10)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/black/icons/black/repeat.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_kayitli_ogrenciler_listeyi_yenile.setIcon(icon1)
        self.btn_kayitli_ogrenciler_listeyi_yenile.setIconSize(QtCore.QSize(32, 32))
        self.btn_kayitli_ogrenciler_listeyi_yenile.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_kayitli_ogrenciler_listeyi_yenile.setObjectName("btn_kayitli_ogrenciler_listeyi_yenile")
        self.horizontalLayout_2.addWidget(self.btn_kayitli_ogrenciler_listeyi_yenile)
        self.btn_kayitli_ogrenciler_yeni_ogrenci_ekle = QtWidgets.QToolButton(self.frame_10)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/others/icons/others/student-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_kayitli_ogrenciler_yeni_ogrenci_ekle.setIcon(icon2)
        self.btn_kayitli_ogrenciler_yeni_ogrenci_ekle.setIconSize(QtCore.QSize(32, 32))
        self.btn_kayitli_ogrenciler_yeni_ogrenci_ekle.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_kayitli_ogrenciler_yeni_ogrenci_ekle.setObjectName("btn_kayitli_ogrenciler_yeni_ogrenci_ekle")
        self.horizontalLayout_2.addWidget(self.btn_kayitli_ogrenciler_yeni_ogrenci_ekle)
        self.btn_kayitli_ogrenciler_ogrenci_bilgi_duzenle = QtWidgets.QToolButton(self.frame_10)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/others/icons/others/e-learning-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_kayitli_ogrenciler_ogrenci_bilgi_duzenle.setIcon(icon3)
        self.btn_kayitli_ogrenciler_ogrenci_bilgi_duzenle.setIconSize(QtCore.QSize(32, 32))
        self.btn_kayitli_ogrenciler_ogrenci_bilgi_duzenle.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_kayitli_ogrenciler_ogrenci_bilgi_duzenle.setObjectName("btn_kayitli_ogrenciler_ogrenci_bilgi_duzenle")
        self.horizontalLayout_2.addWidget(self.btn_kayitli_ogrenciler_ogrenci_bilgi_duzenle)
        self.btn_kayitli_ogrenciler_muhasebe_islemleri = QtWidgets.QToolButton(self.frame_10)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/others/icons/others/point-of-sale-pay-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_kayitli_ogrenciler_muhasebe_islemleri.setIcon(icon4)
        self.btn_kayitli_ogrenciler_muhasebe_islemleri.setIconSize(QtCore.QSize(32, 32))
        self.btn_kayitli_ogrenciler_muhasebe_islemleri.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_kayitli_ogrenciler_muhasebe_islemleri.setObjectName("btn_kayitli_ogrenciler_muhasebe_islemleri")
        self.horizontalLayout_2.addWidget(self.btn_kayitli_ogrenciler_muhasebe_islemleri)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame_10)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_10)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_6.addWidget(self.frame_10)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_9)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.rb_kayitli_ogrenciler_no_sirali = QtWidgets.QRadioButton(self.frame_9)
        self.rb_kayitli_ogrenciler_no_sirali.setObjectName("rb_kayitli_ogrenciler_no_sirali")
        self.horizontalLayout_4.addWidget(self.rb_kayitli_ogrenciler_no_sirali)
        self.rb_kayitli_ogrenciler_isim_sirali = QtWidgets.QRadioButton(self.frame_9)
        self.rb_kayitli_ogrenciler_isim_sirali.setChecked(True)
        self.rb_kayitli_ogrenciler_isim_sirali.setObjectName("rb_kayitli_ogrenciler_isim_sirali")
        self.horizontalLayout_4.addWidget(self.rb_kayitli_ogrenciler_isim_sirali)
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_3.addWidget(self.frame_11)
        self.verticalLayout_6.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_kayitli_ogrenciler_listesi = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_kayitli_ogrenciler_listesi.setObjectName("tableWidget_kayitli_ogrenciler_listesi")
        self.tableWidget_kayitli_ogrenciler_listesi.setColumnCount(0)
        self.tableWidget_kayitli_ogrenciler_listesi.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget_kayitli_ogrenciler_listesi)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_kayitli_ogrenciler_isimlik = QtWidgets.QLabel(self.frame_5)
        self.lbl_kayitli_ogrenciler_isimlik.setText("")
        self.lbl_kayitli_ogrenciler_isimlik.setObjectName("lbl_kayitli_ogrenciler_isimlik")
        self.verticalLayout_5.addWidget(self.lbl_kayitli_ogrenciler_isimlik)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_7)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_2)
        kayitli_ogrenciler.setCentralWidget(self.centralwidget)

        self.retranslateUi(kayitli_ogrenciler)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(kayitli_ogrenciler)

    def retranslateUi(self, kayitli_ogrenciler):
        _translate = QtCore.QCoreApplication.translate
        kayitli_ogrenciler.setWindowTitle(_translate("kayitli_ogrenciler", "Kayıtlı Öğrenciler"))
        self.btn_kayitli_ogrenciler_listeyi_yenile.setText(_translate("kayitli_ogrenciler", "Listeyi Yenile"))
        self.btn_kayitli_ogrenciler_yeni_ogrenci_ekle.setText(_translate("kayitli_ogrenciler", "Yeni Öğrenci Ekle"))
        self.btn_kayitli_ogrenciler_ogrenci_bilgi_duzenle.setText(_translate("kayitli_ogrenciler", "Öğrenci Bilgi Düzenle"))
        self.btn_kayitli_ogrenciler_muhasebe_islemleri.setText(_translate("kayitli_ogrenciler", "Muhasebe İşlemleri"))
        self.label.setText(_translate("kayitli_ogrenciler", "Kayıtlı Öğrenciler:"))
        self.label_2.setText(_translate("kayitli_ogrenciler", "0"))
        self.label_3.setText(_translate("kayitli_ogrenciler", "Sırala:"))
        self.rb_kayitli_ogrenciler_no_sirali.setText(_translate("kayitli_ogrenciler", "No Sıralı"))
        self.rb_kayitli_ogrenciler_isim_sirali.setText(_translate("kayitli_ogrenciler", "İsim Sıralı"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("kayitli_ogrenciler", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("kayitli_ogrenciler", "Tab 2"))
import resources_rc
